// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/localtime/LocalTimeProtocol.proto

package localtime;

public final class LocalTimeProtocol {
  private LocalTimeProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum Continent
      implements com.google.protobuf.ProtocolMessageEnum {
    AFRICA(0, 0),
    AMERICA(1, 1),
    ANTARCTICA(2, 2),
    ARCTIC(3, 3),
    ASIA(4, 4),
    ATLANTIC(5, 5),
    AUSTRALIA(6, 6),
    EUROPE(7, 7),
    INDIAN(8, 8),
    MIDEAST(9, 9),
    PACIFIC(10, 10),
    ;
    
    public static final int AFRICA_VALUE = 0;
    public static final int AMERICA_VALUE = 1;
    public static final int ANTARCTICA_VALUE = 2;
    public static final int ARCTIC_VALUE = 3;
    public static final int ASIA_VALUE = 4;
    public static final int ATLANTIC_VALUE = 5;
    public static final int AUSTRALIA_VALUE = 6;
    public static final int EUROPE_VALUE = 7;
    public static final int INDIAN_VALUE = 8;
    public static final int MIDEAST_VALUE = 9;
    public static final int PACIFIC_VALUE = 10;
    
    
    public final int getNumber() { return value; }
    
    public static Continent valueOf(int value) {
      switch (value) {
        case 0: return AFRICA;
        case 1: return AMERICA;
        case 2: return ANTARCTICA;
        case 3: return ARCTIC;
        case 4: return ASIA;
        case 5: return ATLANTIC;
        case 6: return AUSTRALIA;
        case 7: return EUROPE;
        case 8: return INDIAN;
        case 9: return MIDEAST;
        case 10: return PACIFIC;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<Continent>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Continent>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Continent>() {
            public Continent findValueByNumber(int number) {
              return Continent.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return localtime.LocalTimeProtocol.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final Continent[] VALUES = {
      AFRICA, AMERICA, ANTARCTICA, ARCTIC, ASIA, ATLANTIC, AUSTRALIA, EUROPE, INDIAN, MIDEAST, PACIFIC, 
    };
    
    public static Continent valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private Continent(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:localtime.Continent)
  }
  
  public enum DayOfWeek
      implements com.google.protobuf.ProtocolMessageEnum {
    SUNDAY(0, 1),
    MONDAY(1, 2),
    TUESDAY(2, 3),
    WEDNESDAY(3, 4),
    THURSDAY(4, 5),
    FRIDAY(5, 6),
    SATURDAY(6, 7),
    ;
    
    public static final int SUNDAY_VALUE = 1;
    public static final int MONDAY_VALUE = 2;
    public static final int TUESDAY_VALUE = 3;
    public static final int WEDNESDAY_VALUE = 4;
    public static final int THURSDAY_VALUE = 5;
    public static final int FRIDAY_VALUE = 6;
    public static final int SATURDAY_VALUE = 7;
    
    
    public final int getNumber() { return value; }
    
    public static DayOfWeek valueOf(int value) {
      switch (value) {
        case 1: return SUNDAY;
        case 2: return MONDAY;
        case 3: return TUESDAY;
        case 4: return WEDNESDAY;
        case 5: return THURSDAY;
        case 6: return FRIDAY;
        case 7: return SATURDAY;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<DayOfWeek>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<DayOfWeek>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DayOfWeek>() {
            public DayOfWeek findValueByNumber(int number) {
              return DayOfWeek.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return localtime.LocalTimeProtocol.getDescriptor().getEnumTypes().get(1);
    }
    
    private static final DayOfWeek[] VALUES = {
      SUNDAY, MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, 
    };
    
    public static DayOfWeek valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private DayOfWeek(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:localtime.DayOfWeek)
  }
  
  public interface LocationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .localtime.Continent continent = 1;
    boolean hasContinent();
    localtime.LocalTimeProtocol.Continent getContinent();
    
    // required string city = 2;
    boolean hasCity();
    String getCity();
  }
  public static final class Location extends
      com.google.protobuf.GeneratedMessage
      implements LocationOrBuilder {
    // Use Location.newBuilder() to construct.
    private Location(Builder builder) {
      super(builder);
    }
    private Location(boolean noInit) {}
    
    private static final Location defaultInstance;
    public static Location getDefaultInstance() {
      return defaultInstance;
    }
    
    public Location getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return localtime.LocalTimeProtocol.internal_static_localtime_Location_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return localtime.LocalTimeProtocol.internal_static_localtime_Location_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .localtime.Continent continent = 1;
    public static final int CONTINENT_FIELD_NUMBER = 1;
    private localtime.LocalTimeProtocol.Continent continent_;
    public boolean hasContinent() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public localtime.LocalTimeProtocol.Continent getContinent() {
      return continent_;
    }
    
    // required string city = 2;
    public static final int CITY_FIELD_NUMBER = 2;
    private java.lang.Object city_;
    public boolean hasCity() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          city_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      continent_ = localtime.LocalTimeProtocol.Continent.AFRICA;
      city_ = "";
    }
    public static localtime.LocalTimeProtocol.Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static localtime.LocalTimeProtocol.Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static localtime.LocalTimeProtocol.Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static localtime.LocalTimeProtocol.Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static localtime.LocalTimeProtocol.Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static localtime.LocalTimeProtocol.Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static localtime.LocalTimeProtocol.Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static localtime.LocalTimeProtocol.Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static localtime.LocalTimeProtocol.Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static localtime.LocalTimeProtocol.Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(localtime.LocalTimeProtocol.Location prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements localtime.LocalTimeProtocol.LocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return localtime.LocalTimeProtocol.internal_static_localtime_Location_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return localtime.LocalTimeProtocol.internal_static_localtime_Location_fieldAccessorTable;
      }
      
      // Construct using localtime.LocalTimeProtocol.Location.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        continent_ = localtime.LocalTimeProtocol.Continent.AFRICA;
        bitField0_ = (bitField0_ & ~0x00000001);
        city_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return localtime.LocalTimeProtocol.Location.getDescriptor();
      }
      
      public localtime.LocalTimeProtocol.Location getDefaultInstanceForType() {
        return localtime.LocalTimeProtocol.Location.getDefaultInstance();
      }
      
      public localtime.LocalTimeProtocol.Location build() {
        localtime.LocalTimeProtocol.Location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private localtime.LocalTimeProtocol.Location buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        localtime.LocalTimeProtocol.Location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public localtime.LocalTimeProtocol.Location buildPartial() {
        localtime.LocalTimeProtocol.Location result = new localtime.LocalTimeProtocol.Location(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.continent_ = continent_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.city_ = city_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      private int bitField0_;
      
      // required .localtime.Continent continent = 1;
      private localtime.LocalTimeProtocol.Continent continent_ = localtime.LocalTimeProtocol.Continent.AFRICA;
      public boolean hasContinent() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public localtime.LocalTimeProtocol.Continent getContinent() {
        return continent_;
      }
      public Builder setContinent(localtime.LocalTimeProtocol.Continent value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        continent_ = value;
        onChanged();
        return this;
      }
      public Builder clearContinent() {
        bitField0_ = (bitField0_ & ~0x00000001);
        continent_ = localtime.LocalTimeProtocol.Continent.AFRICA;
        onChanged();
        return this;
      }
      
      // required string city = 2;
      private java.lang.Object city_ = "";
      public boolean hasCity() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCity(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        city_ = value;
        onChanged();
        return this;
      }
      public Builder clearCity() {
        bitField0_ = (bitField0_ & ~0x00000002);
        city_ = getDefaultInstance().getCity();
        onChanged();
        return this;
      }
      void setCity(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        city_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:localtime.Location)
    }
    
    static {
      defaultInstance = new Location(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:localtime.Location)
  }
  
  public interface LocationsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .localtime.Location location = 1;
    java.util.List<localtime.LocalTimeProtocol.Location> 
        getLocationList();
    localtime.LocalTimeProtocol.Location getLocation(int index);
    int getLocationCount();
    java.util.List<? extends localtime.LocalTimeProtocol.LocationOrBuilder> 
        getLocationOrBuilderList();
    localtime.LocalTimeProtocol.LocationOrBuilder getLocationOrBuilder(
        int index);
  }
  public static final class Locations extends
      com.google.protobuf.GeneratedMessage
      implements LocationsOrBuilder {
    // Use Locations.newBuilder() to construct.
    private Locations(Builder builder) {
      super(builder);
    }
    private Locations(boolean noInit) {}
    
    private static final Locations defaultInstance;
    public static Locations getDefaultInstance() {
      return defaultInstance;
    }
    
    public Locations getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return localtime.LocalTimeProtocol.internal_static_localtime_Locations_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return localtime.LocalTimeProtocol.internal_static_localtime_Locations_fieldAccessorTable;
    }
    
    // repeated .localtime.Location location = 1;
    public static final int LOCATION_FIELD_NUMBER = 1;
    private java.util.List<localtime.LocalTimeProtocol.Location> location_;
    public java.util.List<localtime.LocalTimeProtocol.Location> getLocationList() {
      return location_;
    }
    public java.util.List<? extends localtime.LocalTimeProtocol.LocationOrBuilder> 
        getLocationOrBuilderList() {
      return location_;
    }
    public int getLocationCount() {
      return location_.size();
    }
    public localtime.LocalTimeProtocol.Location getLocation(int index) {
      return location_.get(index);
    }
    public localtime.LocalTimeProtocol.LocationOrBuilder getLocationOrBuilder(
        int index) {
      return location_.get(index);
    }
    
    private void initFields() {
      location_ = java.util.Collections.emptyList();
    }
    public static localtime.LocalTimeProtocol.Locations parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static localtime.LocalTimeProtocol.Locations parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static localtime.LocalTimeProtocol.Locations parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static localtime.LocalTimeProtocol.Locations parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static localtime.LocalTimeProtocol.Locations parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static localtime.LocalTimeProtocol.Locations parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static localtime.LocalTimeProtocol.Locations parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static localtime.LocalTimeProtocol.Locations parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static localtime.LocalTimeProtocol.Locations parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static localtime.LocalTimeProtocol.Locations parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(localtime.LocalTimeProtocol.Locations prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements localtime.LocalTimeProtocol.LocationsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return localtime.LocalTimeProtocol.internal_static_localtime_Locations_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return localtime.LocalTimeProtocol.internal_static_localtime_Locations_fieldAccessorTable;
      }
      
      // Construct using localtime.LocalTimeProtocol.Locations.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLocationFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (locationBuilder_ == null) {
          location_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          locationBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return localtime.LocalTimeProtocol.Locations.getDescriptor();
      }
      
      public localtime.LocalTimeProtocol.Locations getDefaultInstanceForType() {
        return localtime.LocalTimeProtocol.Locations.getDefaultInstance();
      }
      
      public localtime.LocalTimeProtocol.Locations build() {
        localtime.LocalTimeProtocol.Locations result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private localtime.LocalTimeProtocol.Locations buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        localtime.LocalTimeProtocol.Locations result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public localtime.LocalTimeProtocol.Locations buildPartial() {
        localtime.LocalTimeProtocol.Locations result = new localtime.LocalTimeProtocol.Locations(this);
        int from_bitField0_ = bitField0_;
        if (locationBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            location_ = java.util.Collections.unmodifiableList(location_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.location_ = location_;
        } else {
          result.location_ = locationBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      private int bitField0_;
      
      // repeated .localtime.Location location = 1;
      private java.util.List<localtime.LocalTimeProtocol.Location> location_ =
        java.util.Collections.emptyList();
      private void ensureLocationIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          location_ = new java.util.ArrayList<localtime.LocalTimeProtocol.Location>(location_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          localtime.LocalTimeProtocol.Location, localtime.LocalTimeProtocol.Location.Builder, localtime.LocalTimeProtocol.LocationOrBuilder> locationBuilder_;
      
      public java.util.List<localtime.LocalTimeProtocol.Location> getLocationList() {
        if (locationBuilder_ == null) {
          return java.util.Collections.unmodifiableList(location_);
        } else {
          return locationBuilder_.getMessageList();
        }
      }
      public int getLocationCount() {
        if (locationBuilder_ == null) {
          return location_.size();
        } else {
          return locationBuilder_.getCount();
        }
      }
      public localtime.LocalTimeProtocol.Location getLocation(int index) {
        if (locationBuilder_ == null) {
          return location_.get(index);
        } else {
          return locationBuilder_.getMessage(index);
        }
      }
      public Builder setLocation(
          int index, localtime.LocalTimeProtocol.Location value) {
        if (locationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLocationIsMutable();
          location_.set(index, value);
          onChanged();
        } else {
          locationBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setLocation(
          int index, localtime.LocalTimeProtocol.Location.Builder builderForValue) {
        if (locationBuilder_ == null) {
          ensureLocationIsMutable();
          location_.set(index, builderForValue.build());
          onChanged();
        } else {
          locationBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addLocation(localtime.LocalTimeProtocol.Location value) {
        if (locationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLocationIsMutable();
          location_.add(value);
          onChanged();
        } else {
          locationBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addLocation(
          int index, localtime.LocalTimeProtocol.Location value) {
        if (locationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLocationIsMutable();
          location_.add(index, value);
          onChanged();
        } else {
          locationBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addLocation(
          localtime.LocalTimeProtocol.Location.Builder builderForValue) {
        if (locationBuilder_ == null) {
          ensureLocationIsMutable();
          location_.add(builderForValue.build());
          onChanged();
        } else {
          locationBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addLocation(
          int index, localtime.LocalTimeProtocol.Location.Builder builderForValue) {
        if (locationBuilder_ == null) {
          ensureLocationIsMutable();
          location_.add(index, builderForValue.build());
          onChanged();
        } else {
          locationBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllLocation(
          java.lang.Iterable<? extends localtime.LocalTimeProtocol.Location> values) {
        if (locationBuilder_ == null) {
          ensureLocationIsMutable();
          super.addAll(values, location_);
          onChanged();
        } else {
          locationBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearLocation() {
        if (locationBuilder_ == null) {
          location_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          locationBuilder_.clear();
        }
        return this;
      }
      public Builder removeLocation(int index) {
        if (locationBuilder_ == null) {
          ensureLocationIsMutable();
          location_.remove(index);
          onChanged();
        } else {
          locationBuilder_.remove(index);
        }
        return this;
      }
      public localtime.LocalTimeProtocol.Location.Builder getLocationBuilder(
          int index) {
        return getLocationFieldBuilder().getBuilder(index);
      }
      public localtime.LocalTimeProtocol.LocationOrBuilder getLocationOrBuilder(
          int index) {
        if (locationBuilder_ == null) {
          return location_.get(index);  } else {
          return locationBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends localtime.LocalTimeProtocol.LocationOrBuilder> 
           getLocationOrBuilderList() {
        if (locationBuilder_ != null) {
          return locationBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(location_);
        }
      }
      public localtime.LocalTimeProtocol.Location.Builder addLocationBuilder() {
        return getLocationFieldBuilder().addBuilder(
            localtime.LocalTimeProtocol.Location.getDefaultInstance());
      }
      public localtime.LocalTimeProtocol.Location.Builder addLocationBuilder(
          int index) {
        return getLocationFieldBuilder().addBuilder(
            index, localtime.LocalTimeProtocol.Location.getDefaultInstance());
      }
      public java.util.List<localtime.LocalTimeProtocol.Location.Builder> 
           getLocationBuilderList() {
        return getLocationFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          localtime.LocalTimeProtocol.Location, localtime.LocalTimeProtocol.Location.Builder, localtime.LocalTimeProtocol.LocationOrBuilder> 
          getLocationFieldBuilder() {
        if (locationBuilder_ == null) {
          locationBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              localtime.LocalTimeProtocol.Location, localtime.LocalTimeProtocol.Location.Builder, localtime.LocalTimeProtocol.LocationOrBuilder>(
                  location_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          location_ = null;
        }
        return locationBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:localtime.Locations)
    }
    
    static {
      defaultInstance = new Locations(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:localtime.Locations)
  }
  
  public interface LocalTimeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint32 year = 1;
    boolean hasYear();
    int getYear();
    
    // required uint32 month = 2;
    boolean hasMonth();
    int getMonth();
    
    // required uint32 dayOfMonth = 4;
    boolean hasDayOfMonth();
    int getDayOfMonth();
    
    // required .localtime.DayOfWeek dayOfWeek = 5;
    boolean hasDayOfWeek();
    localtime.LocalTimeProtocol.DayOfWeek getDayOfWeek();
    
    // required uint32 hour = 6;
    boolean hasHour();
    int getHour();
    
    // required uint32 minute = 7;
    boolean hasMinute();
    int getMinute();
    
    // required uint32 second = 8;
    boolean hasSecond();
    int getSecond();
  }
  public static final class LocalTime extends
      com.google.protobuf.GeneratedMessage
      implements LocalTimeOrBuilder {
    // Use LocalTime.newBuilder() to construct.
    private LocalTime(Builder builder) {
      super(builder);
    }
    private LocalTime(boolean noInit) {}
    
    private static final LocalTime defaultInstance;
    public static LocalTime getDefaultInstance() {
      return defaultInstance;
    }
    
    public LocalTime getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return localtime.LocalTimeProtocol.internal_static_localtime_LocalTime_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return localtime.LocalTimeProtocol.internal_static_localtime_LocalTime_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint32 year = 1;
    public static final int YEAR_FIELD_NUMBER = 1;
    private int year_;
    public boolean hasYear() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getYear() {
      return year_;
    }
    
    // required uint32 month = 2;
    public static final int MONTH_FIELD_NUMBER = 2;
    private int month_;
    public boolean hasMonth() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getMonth() {
      return month_;
    }
    
    // required uint32 dayOfMonth = 4;
    public static final int DAYOFMONTH_FIELD_NUMBER = 4;
    private int dayOfMonth_;
    public boolean hasDayOfMonth() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getDayOfMonth() {
      return dayOfMonth_;
    }
    
    // required .localtime.DayOfWeek dayOfWeek = 5;
    public static final int DAYOFWEEK_FIELD_NUMBER = 5;
    private localtime.LocalTimeProtocol.DayOfWeek dayOfWeek_;
    public boolean hasDayOfWeek() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public localtime.LocalTimeProtocol.DayOfWeek getDayOfWeek() {
      return dayOfWeek_;
    }
    
    // required uint32 hour = 6;
    public static final int HOUR_FIELD_NUMBER = 6;
    private int hour_;
    public boolean hasHour() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getHour() {
      return hour_;
    }
    
    // required uint32 minute = 7;
    public static final int MINUTE_FIELD_NUMBER = 7;
    private int minute_;
    public boolean hasMinute() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getMinute() {
      return minute_;
    }
    
    // required uint32 second = 8;
    public static final int SECOND_FIELD_NUMBER = 8;
    private int second_;
    public boolean hasSecond() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public int getSecond() {
      return second_;
    }
    
    private void initFields() {
      year_ = 0;
      month_ = 0;
      dayOfMonth_ = 0;
      dayOfWeek_ = localtime.LocalTimeProtocol.DayOfWeek.SUNDAY;
      hour_ = 0;
      minute_ = 0;
      second_ = 0;
    }
    public static localtime.LocalTimeProtocol.LocalTime parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static localtime.LocalTimeProtocol.LocalTime parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static localtime.LocalTimeProtocol.LocalTime parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static localtime.LocalTimeProtocol.LocalTime parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static localtime.LocalTimeProtocol.LocalTime parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static localtime.LocalTimeProtocol.LocalTime parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static localtime.LocalTimeProtocol.LocalTime parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static localtime.LocalTimeProtocol.LocalTime parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static localtime.LocalTimeProtocol.LocalTime parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static localtime.LocalTimeProtocol.LocalTime parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(localtime.LocalTimeProtocol.LocalTime prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements localtime.LocalTimeProtocol.LocalTimeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return localtime.LocalTimeProtocol.internal_static_localtime_LocalTime_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return localtime.LocalTimeProtocol.internal_static_localtime_LocalTime_fieldAccessorTable;
      }
      
      // Construct using localtime.LocalTimeProtocol.LocalTime.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        year_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        month_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        dayOfMonth_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        dayOfWeek_ = localtime.LocalTimeProtocol.DayOfWeek.SUNDAY;
        bitField0_ = (bitField0_ & ~0x00000008);
        hour_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        minute_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        second_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return localtime.LocalTimeProtocol.LocalTime.getDescriptor();
      }
      
      public localtime.LocalTimeProtocol.LocalTime getDefaultInstanceForType() {
        return localtime.LocalTimeProtocol.LocalTime.getDefaultInstance();
      }
      
      public localtime.LocalTimeProtocol.LocalTime build() {
        localtime.LocalTimeProtocol.LocalTime result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private localtime.LocalTimeProtocol.LocalTime buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        localtime.LocalTimeProtocol.LocalTime result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public localtime.LocalTimeProtocol.LocalTime buildPartial() {
        localtime.LocalTimeProtocol.LocalTime result = new localtime.LocalTimeProtocol.LocalTime(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.year_ = year_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.month_ = month_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.dayOfMonth_ = dayOfMonth_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.dayOfWeek_ = dayOfWeek_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.hour_ = hour_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.minute_ = minute_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.second_ = second_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      private int bitField0_;
      
      // required uint32 year = 1;
      private int year_ ;
      public boolean hasYear() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getYear() {
        return year_;
      }
      public Builder setYear(int value) {
        bitField0_ |= 0x00000001;
        year_ = value;
        onChanged();
        return this;
      }
      public Builder clearYear() {
        bitField0_ = (bitField0_ & ~0x00000001);
        year_ = 0;
        onChanged();
        return this;
      }
      
      // required uint32 month = 2;
      private int month_ ;
      public boolean hasMonth() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getMonth() {
        return month_;
      }
      public Builder setMonth(int value) {
        bitField0_ |= 0x00000002;
        month_ = value;
        onChanged();
        return this;
      }
      public Builder clearMonth() {
        bitField0_ = (bitField0_ & ~0x00000002);
        month_ = 0;
        onChanged();
        return this;
      }
      
      // required uint32 dayOfMonth = 4;
      private int dayOfMonth_ ;
      public boolean hasDayOfMonth() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getDayOfMonth() {
        return dayOfMonth_;
      }
      public Builder setDayOfMonth(int value) {
        bitField0_ |= 0x00000004;
        dayOfMonth_ = value;
        onChanged();
        return this;
      }
      public Builder clearDayOfMonth() {
        bitField0_ = (bitField0_ & ~0x00000004);
        dayOfMonth_ = 0;
        onChanged();
        return this;
      }
      
      // required .localtime.DayOfWeek dayOfWeek = 5;
      private localtime.LocalTimeProtocol.DayOfWeek dayOfWeek_ = localtime.LocalTimeProtocol.DayOfWeek.SUNDAY;
      public boolean hasDayOfWeek() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public localtime.LocalTimeProtocol.DayOfWeek getDayOfWeek() {
        return dayOfWeek_;
      }
      public Builder setDayOfWeek(localtime.LocalTimeProtocol.DayOfWeek value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        dayOfWeek_ = value;
        onChanged();
        return this;
      }
      public Builder clearDayOfWeek() {
        bitField0_ = (bitField0_ & ~0x00000008);
        dayOfWeek_ = localtime.LocalTimeProtocol.DayOfWeek.SUNDAY;
        onChanged();
        return this;
      }
      
      // required uint32 hour = 6;
      private int hour_ ;
      public boolean hasHour() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getHour() {
        return hour_;
      }
      public Builder setHour(int value) {
        bitField0_ |= 0x00000010;
        hour_ = value;
        onChanged();
        return this;
      }
      public Builder clearHour() {
        bitField0_ = (bitField0_ & ~0x00000010);
        hour_ = 0;
        onChanged();
        return this;
      }
      
      // required uint32 minute = 7;
      private int minute_ ;
      public boolean hasMinute() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getMinute() {
        return minute_;
      }
      public Builder setMinute(int value) {
        bitField0_ |= 0x00000020;
        minute_ = value;
        onChanged();
        return this;
      }
      public Builder clearMinute() {
        bitField0_ = (bitField0_ & ~0x00000020);
        minute_ = 0;
        onChanged();
        return this;
      }
      
      // required uint32 second = 8;
      private int second_ ;
      public boolean hasSecond() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getSecond() {
        return second_;
      }
      public Builder setSecond(int value) {
        bitField0_ |= 0x00000040;
        second_ = value;
        onChanged();
        return this;
      }
      public Builder clearSecond() {
        bitField0_ = (bitField0_ & ~0x00000040);
        second_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:localtime.LocalTime)
    }
    
    static {
      defaultInstance = new LocalTime(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:localtime.LocalTime)
  }
  
  public interface LocalTimesOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .localtime.LocalTime localTime = 1;
    java.util.List<localtime.LocalTimeProtocol.LocalTime> 
        getLocalTimeList();
    localtime.LocalTimeProtocol.LocalTime getLocalTime(int index);
    int getLocalTimeCount();
    java.util.List<? extends localtime.LocalTimeProtocol.LocalTimeOrBuilder> 
        getLocalTimeOrBuilderList();
    localtime.LocalTimeProtocol.LocalTimeOrBuilder getLocalTimeOrBuilder(
        int index);
  }
  public static final class LocalTimes extends
      com.google.protobuf.GeneratedMessage
      implements LocalTimesOrBuilder {
    // Use LocalTimes.newBuilder() to construct.
    private LocalTimes(Builder builder) {
      super(builder);
    }
    private LocalTimes(boolean noInit) {}
    
    private static final LocalTimes defaultInstance;
    public static LocalTimes getDefaultInstance() {
      return defaultInstance;
    }
    
    public LocalTimes getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return localtime.LocalTimeProtocol.internal_static_localtime_LocalTimes_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return localtime.LocalTimeProtocol.internal_static_localtime_LocalTimes_fieldAccessorTable;
    }
    
    // repeated .localtime.LocalTime localTime = 1;
    public static final int LOCALTIME_FIELD_NUMBER = 1;
    private java.util.List<localtime.LocalTimeProtocol.LocalTime> localTime_;
    public java.util.List<localtime.LocalTimeProtocol.LocalTime> getLocalTimeList() {
      return localTime_;
    }
    public java.util.List<? extends localtime.LocalTimeProtocol.LocalTimeOrBuilder> 
        getLocalTimeOrBuilderList() {
      return localTime_;
    }
    public int getLocalTimeCount() {
      return localTime_.size();
    }
    public localtime.LocalTimeProtocol.LocalTime getLocalTime(int index) {
      return localTime_.get(index);
    }
    public localtime.LocalTimeProtocol.LocalTimeOrBuilder getLocalTimeOrBuilder(
        int index) {
      return localTime_.get(index);
    }
    
    private void initFields() {
      localTime_ = java.util.Collections.emptyList();
    }
    public static localtime.LocalTimeProtocol.LocalTimes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static localtime.LocalTimeProtocol.LocalTimes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static localtime.LocalTimeProtocol.LocalTimes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static localtime.LocalTimeProtocol.LocalTimes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static localtime.LocalTimeProtocol.LocalTimes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static localtime.LocalTimeProtocol.LocalTimes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static localtime.LocalTimeProtocol.LocalTimes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static localtime.LocalTimeProtocol.LocalTimes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static localtime.LocalTimeProtocol.LocalTimes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static localtime.LocalTimeProtocol.LocalTimes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(localtime.LocalTimeProtocol.LocalTimes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements localtime.LocalTimeProtocol.LocalTimesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return localtime.LocalTimeProtocol.internal_static_localtime_LocalTimes_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return localtime.LocalTimeProtocol.internal_static_localtime_LocalTimes_fieldAccessorTable;
      }
      
      // Construct using localtime.LocalTimeProtocol.LocalTimes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLocalTimeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (localTimeBuilder_ == null) {
          localTime_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          localTimeBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return localtime.LocalTimeProtocol.LocalTimes.getDescriptor();
      }
      
      public localtime.LocalTimeProtocol.LocalTimes getDefaultInstanceForType() {
        return localtime.LocalTimeProtocol.LocalTimes.getDefaultInstance();
      }
      
      public localtime.LocalTimeProtocol.LocalTimes build() {
        localtime.LocalTimeProtocol.LocalTimes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private localtime.LocalTimeProtocol.LocalTimes buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        localtime.LocalTimeProtocol.LocalTimes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public localtime.LocalTimeProtocol.LocalTimes buildPartial() {
        localtime.LocalTimeProtocol.LocalTimes result = new localtime.LocalTimeProtocol.LocalTimes(this);
        int from_bitField0_ = bitField0_;
        if (localTimeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            localTime_ = java.util.Collections.unmodifiableList(localTime_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.localTime_ = localTime_;
        } else {
          result.localTime_ = localTimeBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      private int bitField0_;
      
      // repeated .localtime.LocalTime localTime = 1;
      private java.util.List<localtime.LocalTimeProtocol.LocalTime> localTime_ =
        java.util.Collections.emptyList();
      private void ensureLocalTimeIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          localTime_ = new java.util.ArrayList<localtime.LocalTimeProtocol.LocalTime>(localTime_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          localtime.LocalTimeProtocol.LocalTime, localtime.LocalTimeProtocol.LocalTime.Builder, localtime.LocalTimeProtocol.LocalTimeOrBuilder> localTimeBuilder_;
      
      public java.util.List<localtime.LocalTimeProtocol.LocalTime> getLocalTimeList() {
        if (localTimeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(localTime_);
        } else {
          return localTimeBuilder_.getMessageList();
        }
      }
      public int getLocalTimeCount() {
        if (localTimeBuilder_ == null) {
          return localTime_.size();
        } else {
          return localTimeBuilder_.getCount();
        }
      }
      public localtime.LocalTimeProtocol.LocalTime getLocalTime(int index) {
        if (localTimeBuilder_ == null) {
          return localTime_.get(index);
        } else {
          return localTimeBuilder_.getMessage(index);
        }
      }
      public Builder setLocalTime(
          int index, localtime.LocalTimeProtocol.LocalTime value) {
        if (localTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLocalTimeIsMutable();
          localTime_.set(index, value);
          onChanged();
        } else {
          localTimeBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setLocalTime(
          int index, localtime.LocalTimeProtocol.LocalTime.Builder builderForValue) {
        if (localTimeBuilder_ == null) {
          ensureLocalTimeIsMutable();
          localTime_.set(index, builderForValue.build());
          onChanged();
        } else {
          localTimeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addLocalTime(localtime.LocalTimeProtocol.LocalTime value) {
        if (localTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLocalTimeIsMutable();
          localTime_.add(value);
          onChanged();
        } else {
          localTimeBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addLocalTime(
          int index, localtime.LocalTimeProtocol.LocalTime value) {
        if (localTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLocalTimeIsMutable();
          localTime_.add(index, value);
          onChanged();
        } else {
          localTimeBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addLocalTime(
          localtime.LocalTimeProtocol.LocalTime.Builder builderForValue) {
        if (localTimeBuilder_ == null) {
          ensureLocalTimeIsMutable();
          localTime_.add(builderForValue.build());
          onChanged();
        } else {
          localTimeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addLocalTime(
          int index, localtime.LocalTimeProtocol.LocalTime.Builder builderForValue) {
        if (localTimeBuilder_ == null) {
          ensureLocalTimeIsMutable();
          localTime_.add(index, builderForValue.build());
          onChanged();
        } else {
          localTimeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllLocalTime(
          java.lang.Iterable<? extends localtime.LocalTimeProtocol.LocalTime> values) {
        if (localTimeBuilder_ == null) {
          ensureLocalTimeIsMutable();
          super.addAll(values, localTime_);
          onChanged();
        } else {
          localTimeBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearLocalTime() {
        if (localTimeBuilder_ == null) {
          localTime_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          localTimeBuilder_.clear();
        }
        return this;
      }
      public Builder removeLocalTime(int index) {
        if (localTimeBuilder_ == null) {
          ensureLocalTimeIsMutable();
          localTime_.remove(index);
          onChanged();
        } else {
          localTimeBuilder_.remove(index);
        }
        return this;
      }
      public localtime.LocalTimeProtocol.LocalTime.Builder getLocalTimeBuilder(
          int index) {
        return getLocalTimeFieldBuilder().getBuilder(index);
      }
      public localtime.LocalTimeProtocol.LocalTimeOrBuilder getLocalTimeOrBuilder(
          int index) {
        if (localTimeBuilder_ == null) {
          return localTime_.get(index);  } else {
          return localTimeBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends localtime.LocalTimeProtocol.LocalTimeOrBuilder> 
           getLocalTimeOrBuilderList() {
        if (localTimeBuilder_ != null) {
          return localTimeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(localTime_);
        }
      }
      public localtime.LocalTimeProtocol.LocalTime.Builder addLocalTimeBuilder() {
        return getLocalTimeFieldBuilder().addBuilder(
            localtime.LocalTimeProtocol.LocalTime.getDefaultInstance());
      }
      public localtime.LocalTimeProtocol.LocalTime.Builder addLocalTimeBuilder(
          int index) {
        return getLocalTimeFieldBuilder().addBuilder(
            index, localtime.LocalTimeProtocol.LocalTime.getDefaultInstance());
      }
      public java.util.List<localtime.LocalTimeProtocol.LocalTime.Builder> 
           getLocalTimeBuilderList() {
        return getLocalTimeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          localtime.LocalTimeProtocol.LocalTime, localtime.LocalTimeProtocol.LocalTime.Builder, localtime.LocalTimeProtocol.LocalTimeOrBuilder> 
          getLocalTimeFieldBuilder() {
        if (localTimeBuilder_ == null) {
          localTimeBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              localtime.LocalTimeProtocol.LocalTime, localtime.LocalTimeProtocol.LocalTime.Builder, localtime.LocalTimeProtocol.LocalTimeOrBuilder>(
                  localTime_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          localTime_ = null;
        }
        return localTimeBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:localtime.LocalTimes)
    }
    
    static {
      defaultInstance = new LocalTimes(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:localtime.LocalTimes)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_localtime_Location_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_localtime_Location_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_localtime_Locations_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_localtime_Locations_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_localtime_LocalTime_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_localtime_LocalTime_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_localtime_LocalTimes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_localtime_LocalTimes_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%src/localtime/LocalTimeProtocol.proto\022" +
      "\tlocaltime\"A\n\010Location\022\'\n\tcontinent\030\001 \002(" +
      "\0162\024.localtime.Continent\022\014\n\004city\030\002 \002(\t\"2\n" +
      "\tLocations\022%\n\010location\030\001 \003(\0132\023.localtime" +
      ".Location\"\223\001\n\tLocalTime\022\014\n\004year\030\001 \002(\r\022\r\n" +
      "\005month\030\002 \002(\r\022\022\n\ndayOfMonth\030\004 \002(\r\022\'\n\tdayO" +
      "fWeek\030\005 \002(\0162\024.localtime.DayOfWeek\022\014\n\004hou" +
      "r\030\006 \002(\r\022\016\n\006minute\030\007 \002(\r\022\016\n\006second\030\010 \002(\r\"" +
      "5\n\nLocalTimes\022\'\n\tlocalTime\030\001 \003(\0132\024.local" +
      "time.LocalTime*\231\001\n\tContinent\022\n\n\006AFRICA\020\000",
      "\022\013\n\007AMERICA\020\001\022\016\n\nANTARCTICA\020\002\022\n\n\006ARCTIC\020" +
      "\003\022\010\n\004ASIA\020\004\022\014\n\010ATLANTIC\020\005\022\r\n\tAUSTRALIA\020\006" +
      "\022\n\n\006EUROPE\020\007\022\n\n\006INDIAN\020\010\022\013\n\007MIDEAST\020\t\022\013\n" +
      "\007PACIFIC\020\n*g\n\tDayOfWeek\022\n\n\006SUNDAY\020\001\022\n\n\006M" +
      "ONDAY\020\002\022\013\n\007TUESDAY\020\003\022\r\n\tWEDNESDAY\020\004\022\014\n\010T" +
      "HURSDAY\020\005\022\n\n\006FRIDAY\020\006\022\014\n\010SATURDAY\020\007B\002H\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_localtime_Location_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_localtime_Location_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_localtime_Location_descriptor,
              new java.lang.String[] { "Continent", "City", },
              localtime.LocalTimeProtocol.Location.class,
              localtime.LocalTimeProtocol.Location.Builder.class);
          internal_static_localtime_Locations_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_localtime_Locations_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_localtime_Locations_descriptor,
              new java.lang.String[] { "Location", },
              localtime.LocalTimeProtocol.Locations.class,
              localtime.LocalTimeProtocol.Locations.Builder.class);
          internal_static_localtime_LocalTime_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_localtime_LocalTime_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_localtime_LocalTime_descriptor,
              new java.lang.String[] { "Year", "Month", "DayOfMonth", "DayOfWeek", "Hour", "Minute", "Second", },
              localtime.LocalTimeProtocol.LocalTime.class,
              localtime.LocalTimeProtocol.LocalTime.Builder.class);
          internal_static_localtime_LocalTimes_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_localtime_LocalTimes_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_localtime_LocalTimes_descriptor,
              new java.lang.String[] { "LocalTime", },
              localtime.LocalTimeProtocol.LocalTimes.class,
              localtime.LocalTimeProtocol.LocalTimes.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
